[package]
name = "warc-parquet"
version = "0.1.3"
edition = "2021"
description = "A simple tool for converting WARC files to Parquet files."
license = "MIT"
keywords = ["warc", "parquet"]
repository = "https://github.com/maxcountryman/warc-parquet"

[dependencies]
arrow = "16.0.0"
chrono = "0.4.19"
parquet = "16.0.0"

[dependencies.clap]
version = "3.2.5"
features = ["derive"]

[dependencies.warc]
version = "0.3.1"
features = ["gzip"]
