[package]
name = "warc-parquet"
version = "0.1.0"
edition = "2021"
description = "A simple tool for converting WARC files to Parquet files."
license = "MIT"

[dependencies]
arrow = "16.0.0"
chrono = "0.4.19"
parquet = "16.0.0"
structopt = "0.3.26"
warc = "0.3.1"
